version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - '4200:4200'
      - '9876:9876'
    container_name: app
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run dev"
