# Stage 1: Compile and Build angular codebase
# Use official node image as the base image
FROM node:latest

# Set the working directory
WORKDIR /app
RUN npm install -g @angular/cli

RUN apt-get update
RUN curl -LO  https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install -y ./google-chrome-stable_current_amd64.deb
RUN rm google-chrome-stable_current_amd64.deb
RUN export CHROME_BIN=/usr/bin/google-chrome
# Check chrome version
RUN echo "Chrome: " && google-chrome --version

